[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
]
test = "test"
solc = "0.8.29"
via_ir = true

[profile.settings]
optimizer = true
optimizer_runs = 200
