[package]
name = "method"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "^2.0.2", default-features = false, features = ['std'] }
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10"
